import {
  Achievement,
  FounderSkillType,
  InvestorSkillType,
  JurySkillType,
  LibraryConcept,
  MiniChallenge,
  PlayerSkill,
  Quest,
  UnyCoachPrompt,
} from "./academy-types";

export const FOUNDER_SKILLS_LIST: FounderSkillType[] = [
  "Problem Selection",
  "Customer Discovery",
  "Product",
  "Sales",
  "Marketing",
  "Finance",
  "Fundraising",
  "Leadership",
  "Operations",
  "Strategy",
];

export const INVESTOR_SKILLS_LIST: InvestorSkillType[] = [
  "Market Analysis",
  "Founder Assessment",
  "Traction Analysis",
  "Unit Economics",
  "Valuation",
  "Term Sheets",
  "Portfolio Construction",
  "Risk Management",
  "Deal Sourcing",
  "Investment Strategy",
];

export const JURY_SKILLS_LIST: JurySkillType[] = [
  "Pitch Evaluation",
  "Market Evaluation",
  "Team Evaluation",
  "Traction Evaluation",
  "Business Model Evaluation",
  "Risk Assessment",
  "Investment Thesis",
];

export function getInitialSkills(): PlayerSkill[] {
  const skills: PlayerSkill[] = [];

  FOUNDER_SKILLS_LIST.forEach((s) => {
    skills.push({
      id: `skill-f-${s.toLowerCase().replace(/\s+/g, "-")}`,
      name: s,
      category: "FOUNDER",
      level: 1,
      xp: 0,
      xpToNextLevel: 100,
    });
  });

  INVESTOR_SKILLS_LIST.forEach((s) => {
    skills.push({
      id: `skill-i-${s.toLowerCase().replace(/\s+/g, "-")}`,
      name: s,
      category: "INVESTOR",
      level: 1,
      xp: 0,
      xpToNextLevel: 100,
    });
  });

  JURY_SKILLS_LIST.forEach((s) => {
    skills.push({
      id: `skill-j-${s.toLowerCase().replace(/\s+/g, "-")}`,
      name: s,
      category: "JURY",
      level: 1,
      xp: 0,
      xpToNextLevel: 100,
    });
  });

  return skills;
}

export const INITIAL_QUESTS: Quest[] = [
  {
    id: "quest-1",
    title: "Genesis Venture",
    description: "Form your first startup company and receive $100,000 founder treasury.",
    category: "FOUNDER",
    unlockTier: 1,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 150 },
    rewardBadge: "Genesis Founder",
    learningTakeaway: "Starting requires identifying a genuine problem, market corridor, and business model.",
  },
  {
    id: "quest-2",
    title: "First Traction Sprint",
    description: "Deploy capital into product or marketing to reach at least 250 active customers.",
    category: "FOUNDER",
    unlockTier: 1,
    targetCount: 250,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 200 },
    learningTakeaway: "Building features is not enough; sustainable startups generate organic customer demand.",
  },
  {
    id: "quest-3",
    title: "Master Runway Discipline",
    description: "Advance 2 months forward while maintaining at least 3.0 months of cash runway.",
    category: "FOUNDER",
    unlockTier: 2,
    targetCount: 2,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 250 },
    learningTakeaway: "Runway is oxygen. Increasing burn without proportional revenue expansion triggers distress.",
  },
  {
    id: "quest-4",
    title: "Pitch The Street",
    description: "Deliver a pitch deck to an institutional venture capital archetype (Generalist, Specialist, or Operator).",
    category: "FOUNDER",
    unlockTier: 2,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 300 },
    learningTakeaway: "Pitching forces alignment between your intrinsic valuation and investor expectations.",
  },
  {
    id: "quest-5",
    title: "Close The Round",
    description: "Accept a term sheet and execute cap table dilution to raise growth capital.",
    category: "FOUNDER",
    unlockTier: 3,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 400 },
    rewardBadge: "Capitalized",
    learningTakeaway: "Dilution is normal: owning 80% of a $5M company is worth far more than 100% of zero.",
  },
  {
    id: "quest-6",
    title: "The Viral Handshake",
    description: "Share your company deal room with a friend and complete a peer investment.",
    category: "FOUNDER",
    unlockTier: 3,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 350 },
    learningTakeaway: "The strongest venture ecosystems grow organically through network effects and peer syndication.",
  },
  {
    id: "quest-7",
    title: "Angel Debut",
    description: "Switch to Investor mode and deploy at least $25,000 Investor Capital into a breakout startup.",
    category: "INVESTOR",
    unlockTier: 4,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "INVESTOR", amount: 350 },
    learningTakeaway: "As an investor, you underwrite team execution speed, defensible moats, and unit economics.",
  },
  {
    id: "quest-8",
    title: "Lead From The Front",
    description: "Establish a venture syndicate with at least 10% leader skin-in-the-game commitment.",
    category: "SYNDICATE",
    unlockTier: 5,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "SYNDICATE", amount: 500 },
    rewardBadge: "Syndicate Lead",
    learningTakeaway: "Syndicates pool high-conviction capital. Skin-in-the-game aligns leader incentives with members.",
  },
  {
    id: "quest-9",
    title: "The Liquidity Event",
    description: "Orchestrate a successful acquisition or public IPO exit and reinvest proceeds.",
    category: "FOUNDER",
    unlockTier: 5,
    targetCount: 1,
    currentProgress: 0,
    isCompleted: false,
    rewardXP: { category: "FOUNDER", amount: 750 },
    rewardBadge: "Unicorn Alum",
    learningTakeaway: "Exits return liquidity to founders and investors, creating super-angels who fund the next generation.",
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-first-customer",
    title: "First Customer",
    description: "Acquire your first users through product and marketing sprints.",
    category: "FOUNDER",
    icon: "👥",
    isUnlocked: false,
    learningTakeaway: "The first 10 customers prove value hypothesis; the next 1,000 prove distribution.",
  },
  {
    id: "ach-first-revenue",
    title: "First Revenue Dollar",
    description: "Cross $5,000 monthly revenue milestone.",
    category: "FOUNDER",
    icon: "💵",
    isUnlocked: false,
    learningTakeaway: "Revenue validates willingness-to-pay better than any pitch deck.",
  },
  {
    id: "ach-first-pitch",
    title: "Into The Arena",
    description: "Deliver your first pitch to an institutional VC.",
    category: "FOUNDER",
    icon: "🎤",
    isUnlocked: false,
    learningTakeaway: "Facing investor critique is the fastest way to stress-test your business model.",
  },
  {
    id: "ach-first-rejection",
    title: "The Constructive Pass",
    description: "Receive an investor rejection with constructive feedback reason.",
    category: "FOUNDER",
    icon: "🛡️",
    isUnlocked: false,
    learningTakeaway: "Rejections reveal blind spots: overvalued asks, weak traction, or insufficient moats.",
  },
  {
    id: "ach-first-funding",
    title: "Series Closed",
    description: "Accept a term sheet and close a venture funding round.",
    category: "FOUNDER",
    icon: "🤝",
    isUnlocked: false,
    learningTakeaway: "Fundraising is not a victory—it is a commitment to scale aggressively with investor capital.",
  },
  {
    id: "ach-first-investment",
    title: "Check Writer",
    description: "Deploy virtual capital into another founder's startup.",
    category: "INVESTOR",
    icon: "💼",
    isUnlocked: false,
    learningTakeaway: "Writing checks teaches you how founders think and why valuation multiples compress.",
  },
  {
    id: "ach-first-follow-on",
    title: "Double Down",
    description: "Invest in an existing portfolio company a second time.",
    category: "INVESTOR",
    icon: "⚡",
    isUnlocked: false,
    learningTakeaway: "Venture returns follow a power law: reserve dry powder to back your breakout winners.",
  },
  {
    id: "ach-first-syndicate",
    title: "Syndicate Commander",
    description: "Create an investment syndicate with 10% leader commitment.",
    category: "SYNDICATE",
    icon: "🌐",
    isUnlocked: false,
    learningTakeaway: "Leading a syndicate turns you from a solo angel into an institutional capital allocator.",
  },
  {
    id: "ach-first-exit",
    title: "Unicorn Liquidity",
    description: "Complete an acquisition or IPO exit.",
    category: "FOUNDER",
    icon: "🦄",
    isUnlocked: false,
    learningTakeaway: "An exit recycles capital and reputation back into the ecosystem.",
  },
  {
    id: "ach-first-10x",
    title: "10x Return Club",
    description: "Achieve a 10x or greater virtual return (MOIC) on an investment.",
    category: "INVESTOR",
    icon: "🚀",
    isUnlocked: false,
    learningTakeaway: "Power law returns compensate for early-stage portfolio write-offs.",
  },
];

export const UNY_COACH_PROMPTS: Record<string, UnyCoachPrompt> = {
  FIRST_COMPANY_CREATED: {
    id: "coach-first-comp",
    trigger: "FIRST_COMPANY_CREATED",
    title: "Welcome to UNYQUEST",
    message: "You've formed your startup with $100K treasury. Build product or acquire users, but watch your runway.",
    whyConceptKey: "runway",
    suggestedAction: "Execute your first operating action.",
  },
  FIRST_ACTION_SPENT: {
    id: "coach-first-spend",
    trigger: "FIRST_ACTION_SPENT",
    title: "The Trade-Off",
    message: "Every action has consequences: hiring adds permanent payroll burn, marketing drains immediate cash.",
    whyConceptKey: "burn_rate",
    suggestedAction: "Monitor how your runway shifted.",
  },
  RUNWAY_WARNING: {
    id: "coach-runway-warn",
    trigger: "RUNWAY_WARNING",
    title: "Runway Below 3 Months",
    message: "Your runway is dipping below 3 months. Cut burn with Operations or begin preparing your VC pitch deck.",
    whyConceptKey: "runway",
    suggestedAction: "Head to Pitch Arena or improve operations.",
  },
  RUNWAY_CRITICAL: {
    id: "coach-runway-crit",
    trigger: "RUNWAY_CRITICAL",
    title: "Critical Cash Warning",
    message: "Under 1 month of cash remaining. If cash reaches $0, the company enters distress mode.",
    whyConceptKey: "distress",
    suggestedAction: "Invite a friend investor or raise bridge funding immediately.",
  },
  DISTRESS_MODE: {
    id: "coach-distress",
    trigger: "DISTRESS_MODE",
    title: "Distress Mode Activated",
    message: "Your company has run out of cash. Restructure immediately via an emergency bridge or friendly liquidation.",
    whyConceptKey: "distress",
    suggestedAction: "Review restructuring options.",
  },
  FIRST_PITCH_PASS: {
    id: "coach-pitch-pass",
    trigger: "FIRST_PITCH_PASS",
    title: "Rejection is Data",
    message: "Investors passed because your valuation ask outpaced current traction. Build traction or lower the ask.",
    whyConceptKey: "valuation",
    suggestedAction: "Adjust valuation ask and pitch again.",
  },
  FIRST_TERM_SHEET: {
    id: "coach-term-sheet",
    trigger: "FIRST_TERM_SHEET",
    title: "Term Sheet Received!",
    message: "Inspect pre-money valuation and ownership dilution. Accept, reject, or negotiate a counter-offer.",
    whyConceptKey: "dilution",
    suggestedAction: "Accept or counter the term sheet.",
  },
  RAPID_BURN_MISTAKE: {
    id: "coach-rapid-burn",
    trigger: "RAPID_BURN_MISTAKE",
    title: "Burn Exceeding Traction",
    message: "You've increased hiring burn faster than customer revenue. Growth without unit economics creates insolvency.",
    whyConceptKey: "burn_rate",
    suggestedAction: "Streamline operations to reduce monthly burn.",
  },
  VALUATION_OVERREACH: {
    id: "coach-valuation-overreach",
    trigger: "VALUATION_OVERREACH",
    title: "Valuation Overreach",
    message: "Asking for a valuation greater than 1.5x intrinsic traction triggers steep rejection penalties.",
    whyConceptKey: "valuation",
    suggestedAction: "Align valuation ask with ARR multiples.",
  },
};

export const VENTURE_LIBRARY: LibraryConcept[] = [
  {
    key: "runway",
    title: "Cash Runway",
    category: "Finance",
    definition: "The number of months a startup can continue operating before running out of liquid cash, calculated as Cash divided by Monthly Net Burn.",
    whyItMatters: "Without runway, a startup dies regardless of product quality. Maintaining at least 3-6 months ensures room to fundraise or achieve breakeven.",
    example: "If you have $60,000 cash and burn $15,000/month, your runway is exactly 4.0 months.",
    inGameMetric: "Displayed prominently as RUNWAY: X.X MO in the Founder HQ.",
  },
  {
    key: "burn_rate",
    title: "Monthly Burn Rate",
    category: "Finance",
    definition: "The net amount of capital a company spends each month exceeding its incoming revenue.",
    whyItMatters: "High burn accelerates product development but drastically shortens your lifespan between funding rounds.",
    example: "Hiring lead engineers increases burn permanently by $4,000/month in payroll obligations.",
    inGameMetric: "Monthly Burn in the company metrics grid.",
  },
  {
    key: "valuation",
    title: "Valuation (Pre & Post-Money)",
    category: "Valuation",
    definition: "Pre-money is the company value before new investment; Post-money is Pre-money plus the investment amount.",
    whyItMatters: "Valuation directly determines how much ownership dilution founders suffer to raise a given check size.",
    example: "$250K invested into a $1.75M post-money company yields 14.3% equity ($250k / $1.75M).",
    inGameMetric: "Valuation in Founder HUD and Term Sheet Cards.",
  },
  {
    key: "dilution",
    title: "Equity Dilution",
    category: "Equity",
    definition: "The reduction in existing shareholders' ownership percentages caused by issuing new shares to investors.",
    whyItMatters: "Dilution is normal and necessary: a smaller percentage of a high-value scaled company is worth far more than 100% of zero.",
    example: "If you own 100% and sell 20% in a Seed round, you retain 80% of a capitalized company.",
    inGameMetric: "Founder Ownership % in company cap table.",
  },
  {
    key: "cac_ltv",
    title: "Unit Economics (CAC vs LTV)",
    category: "Revenue",
    definition: "Customer Acquisition Cost (CAC) is the cost to win a buyer; Lifetime Value (LTV) is total profit generated by that customer.",
    whyItMatters: "Startups must achieve LTV > 3x CAC to build sustainable, high-margin software operating leverage.",
    example: "If you spend $18K marketing to acquire 300 customers, your acquisition cost is $60 per user.",
    inGameMetric: "Marketing Action trade-off and revenue growth.",
  },
  {
    key: "distress",
    title: "Distress Mode & Restructuring",
    category: "Finance",
    definition: "The insolvency state entered when company cash reaches zero while monthly expenses continue.",
    whyItMatters: "Distress forces emergency decisions: accepting high-dilution bridge capital, aggressive downsizing, or bankruptcy.",
    example: "A founder in distress must trade 15% equity for an immediate $25K bridge or shut down.",
    inGameMetric: "Distress Alert Banner when cash <= 0.",
  },
  {
    key: "syndicate",
    title: "Investment Syndicates",
    category: "Syndicates",
    definition: "A special purpose vehicle allowing multiple angel investors to pool capital behind a lead investor into a single startup check.",
    whyItMatters: "Syndicates let angels participate in competitive institutional rounds with pro-rata ownership.",
    example: "A lead commits $25K (10%), four members commit $25K each, deploying a unified $125K check.",
    inGameMetric: "Syndicate Hub and Cap Table syndicate entries.",
  },
  {
    key: "moic",
    title: "Multiple on Invested Capital (MOIC)",
    category: "Investing",
    definition: "The multiple of cash returned or unrealized value relative to the original check size.",
    whyItMatters: "Venture capital performance is benchmarked by MOIC: top-tier venture portfolios target 3.0x to 10.0x+ aggregate returns.",
    example: "$50K invested that is now worth $200K represents a 4.0x MOIC.",
    inGameMetric: "Virtual MOIC in the Investor Dashboard.",
  },
  {
    key: "power_law",
    title: "The Venture Power Law",
    category: "Investing",
    definition: "The mathematical reality that a tiny fraction of outlier startups generate the overwhelming majority of all investment returns.",
    whyItMatters: "Concentrating in 1 deal carries extreme risk; diversifying across 5-10 deals increases exposure to unicorn winners.",
    example: "In a 10-company portfolio, 6 fail, 3 return capital, and 1 delivers a 20x return driving the fund.",
    inGameMetric: "Winners vs Failures counters in Investor Portfolio.",
  },
];

export const MINI_CHALLENGES: MiniChallenge[] = [
  {
    id: "chal-1",
    title: "The Runway Crunch vs Bridge Dilemma",
    scenario: "Your startup has $15,000 cash remaining with a $12,000 monthly burn (Runway: 1.2 months). An angel offers an emergency $50,000 check, but demands 20% equity at a discounted $250K pre-money valuation.",
    contextMetrics: { cash: 15_000, burn: 12_000, runway: 1.2, offer: "$50K for 20% equity" },
    options: [
      {
        id: "opt-accept",
        label: "Accept High-Dilution Bridge ($50K for 20%)",
        consequence: "You survive! Runway extends to 5.4 months, but founder ownership dilutes by 20%. You learned: cash preservation precedes valuation vanity.",
        xpGained: 100,
        skillCategory: "FOUNDER",
        skillName: "Finance",
      },
      {
        id: "opt-cut",
        label: "Reject Offer & Cut Burn by 50% Through Downsizing",
        consequence: "You preserve your equity, but product velocity slows down by 40%. Runway extends to 2.5 months. You learned: burn reduction buys time at execution cost.",
        xpGained: 120,
        skillCategory: "FOUNDER",
        skillName: "Operations",
      },
      {
        id: "opt-counter",
        label: "Counter at $50K for 12% with Quarterly Observer Rights",
        consequence: "The angel respects your discipline and agrees to 14%! You learned: professional negotiation hinges on reasoned counter-proposals.",
        xpGained: 150,
        skillCategory: "FOUNDER",
        skillName: "Fundraising",
      },
    ],
  },
  {
    id: "chal-2",
    title: "Concentration vs Diversification",
    scenario: "You have $100,000 in Investor Capital. A high-flying AI startup wants your full $100K check, while three promising regional marketplaces are each raising $30K tranches.",
    contextMetrics: { cash: 100_000, burn: 0, runway: 99.9, offer: "1 x $100K or 3 x $30K" },
    options: [
      {
        id: "opt-concentrate",
        label: "Write $100K Solo Check (Maximum Concentration)",
        consequence: "High conviction! If this startup wins, your MOIC will be massive; if it stalls, your portfolio suffers complete loss. You learned: concentration magnifies volatility.",
        xpGained: 100,
        skillCategory: "INVESTOR",
        skillName: "Risk Management",
      },
      {
        id: "opt-diversify",
        label: "Spread $90K Across 3 Startups (Diversified Basket)",
        consequence: "Classic portfolio theory! You reduce single-company insolvency risk while leaving $10K dry powder for follow-ons. You learned: diversification guards against early mortality.",
        xpGained: 150,
        skillCategory: "INVESTOR",
        skillName: "Portfolio Construction",
      },
    ],
  },
];
