import {
  StartupArchetypeSeed,
  InvestorArchetype,
} from "./types";

export interface NPCInvestor {
  id: string;
  name: string;
  firm: string;
  archetype: InvestorArchetype;
  avatar: string;
  check_size_range: [number, number];
  preferred_sectors: string[];
  reputation: number;
  bio: string;
  rejectionQuotes: string[];
  interestQuotes: string[];
  termSheetQuotes: string[];
}

export const SEED_STARTUP_ARCHETYPES: StartupArchetypeSeed[] = [
  {
    name: "FleetMind AI",
    tagline: "Autonomous routing and freight dispatch for multi-modal logistics",
    sector: "Logistics",
    market: "Global",
    business_model: "SaaS",
    founder_strengths: ["Technical", "Operations"],
    tam: 18_000_000_000,
    initial_users: 120,
    initial_revenue: 18_000,
    initial_burn: 12_000,
    difficulty: "MEDIUM",
    risk_profile: "High customer acquisition cost in legacy freight market",
  },
  {
    name: "AfriPay Corridor",
    tagline: "Cross-border instant B2B settlement across 14 African currencies",
    sector: "Fintech",
    market: "Africa",
    business_model: "Transaction",
    founder_strengths: ["Domain expert", "Sales"],
    tam: 24_000_000_000,
    initial_users: 280,
    initial_revenue: 35_000,
    initial_burn: 18_000,
    difficulty: "HARD",
    risk_profile: "FX regulatory exposure and central bank compliance",
  },
  {
    name: "DocDirect Care",
    tagline: "Specialist healthcare marketplace with on-demand telemedicine",
    sector: "Healthcare",
    market: "Europe",
    business_model: "Marketplace",
    founder_strengths: ["Product", "Operations"],
    tam: 9_500_000_000,
    initial_users: 850,
    initial_revenue: 22_000,
    initial_burn: 14_000,
    difficulty: "MEDIUM",
    risk_profile: "Two-sided liquidity bootstrapping friction",
  },
  {
    name: "SitePulse Build",
    tagline: "Jobsite safety & automated subcontractor progress tracking SaaS",
    sector: "SaaS",
    market: "Americas",
    business_model: "Subscription",
    founder_strengths: ["Sales", "Domain expert"],
    tam: 7_200_000_000,
    initial_users: 65,
    initial_revenue: 14_000,
    initial_burn: 9_000,
    difficulty: "EASY",
    risk_profile: "Long enterprise construction procurement cycles",
  },
  {
    name: "TerraScope Zero",
    tagline: "Scope 1-3 automated carbon footprint auditing for manufacturing",
    sector: "Climate",
    market: "Europe",
    business_model: "Enterprise",
    founder_strengths: ["Domain expert", "Technical"],
    tam: 15_000_000_000,
    initial_users: 42,
    initial_revenue: 28_000,
    initial_burn: 16_000,
    difficulty: "MEDIUM",
    risk_profile: "Evolving EU carbon tax legislation and verification standards",
  },
  {
    name: "ChefConnect Direct",
    tagline: "Farm-to-restaurant wholesale marketplace eliminating middlemen",
    sector: "Food",
    market: "Americas",
    business_model: "Marketplace",
    founder_strengths: ["Operations", "Distribution"],
    tam: 11_000_000_000,
    initial_users: 320,
    initial_revenue: 40_000,
    initial_burn: 22_000,
    difficulty: "HARD",
    risk_profile: "Perishable inventory logistics and thin margins",
  },
  {
    name: "TenantFlow OS",
    tagline: "AI lease abstraction and predictive maintenance for commercial REITs",
    sector: "PropTech",
    market: "Global",
    business_model: "SaaS",
    founder_strengths: ["Product", "Sales"],
    tam: 8_800_000_000,
    initial_users: 95,
    initial_revenue: 19_000,
    initial_burn: 11_000,
    difficulty: "EASY",
    risk_profile: "Commercial real estate market interest rate sensitivity",
  },
  {
    name: "SkillForge Micro",
    tagline: "Interactive technical micro-credentialing for engineering teams",
    sector: "Education",
    market: "Global",
    business_model: "Subscription",
    founder_strengths: ["Technical", "Product"],
    tam: 6_500_000_000,
    initial_users: 1400,
    initial_revenue: 15_000,
    initial_burn: 8_000,
    difficulty: "EASY",
    risk_profile: "Competitive commoditization from free open-source content",
  },
  {
    name: "CipherGuard AI",
    tagline: "Zero-trust autonomous identity verification for hybrid enterprises",
    sector: "AI",
    market: "Americas",
    business_model: "Enterprise",
    founder_strengths: ["Technical", "Domain expert"],
    tam: 22_000_000_000,
    initial_users: 50,
    initial_revenue: 32_000,
    initial_burn: 20_000,
    difficulty: "HARD",
    risk_profile: "High customer trust threshold and entrenched incumbents",
  },
  {
    name: "OmniPay B2B",
    tagline: "Embedded net-60 working capital financing for wholesale merchants",
    sector: "Fintech",
    market: "Middle East",
    business_model: "Transaction",
    founder_strengths: ["Domain expert", "Sales"],
    tam: 19_000_000_000,
    initial_users: 180,
    initial_revenue: 26_000,
    initial_burn: 15_000,
    difficulty: "MEDIUM",
    risk_profile: "Underwriting default risk during economic downturns",
  },
  {
    name: "AgriRoots Yield",
    tagline: "IoT soil analytics and peer-to-peer fertilizer input exchange",
    sector: "Marketplace",
    market: "Asia",
    business_model: "Marketplace",
    founder_strengths: ["Domain expert", "Operations"],
    tam: 14_000_000_000,
    initial_users: 920,
    initial_revenue: 17_000,
    initial_burn: 10_000,
    difficulty: "MEDIUM",
    risk_profile: "Weather seasonality and rural connectivity gaps",
  },
  {
    name: "NomadPass Hub",
    tagline: "Subscription pass for global co-working and short-stay apartments",
    sector: "Consumer",
    market: "Europe",
    business_model: "Subscription",
    founder_strengths: ["Product", "Distribution"],
    tam: 5_200_000_000,
    initial_users: 2100,
    initial_revenue: 31_000,
    initial_burn: 19_000,
    difficulty: "MEDIUM",
    risk_profile: "High consumer churn and landlord contract concentration",
  },
  {
    name: "LedgerBooks Cloud",
    tagline: "Tax-compliant automated bookkeeping engine for European SMBs",
    sector: "SaaS",
    market: "Europe",
    business_model: "SaaS",
    founder_strengths: ["Technical", "Product"],
    tam: 8_100_000_000,
    initial_users: 480,
    initial_revenue: 24_000,
    initial_burn: 11_000,
    difficulty: "EASY",
    risk_profile: "Fragmented national accounting standards per EU member state",
  },
  {
    name: "CarbonCredit Ex",
    tagline: "Satellite-verified biodiversity and carbon offset marketplace",
    sector: "Climate",
    market: "Global",
    business_model: "Transaction",
    founder_strengths: ["Domain expert", "Technical"],
    tam: 16_500_000_000,
    initial_users: 88,
    initial_revenue: 30_000,
    initial_burn: 17_000,
    difficulty: "HARD",
    risk_profile: "Greenwashing reputational risks and audit certification latency",
  },
  {
    name: "TalentScout Neural",
    tagline: "AI technical coding interview evaluator reducing recruiter bias",
    sector: "AI",
    market: "Americas",
    business_model: "SaaS",
    founder_strengths: ["Technical", "Distribution"],
    tam: 12_000_000_000,
    initial_users: 310,
    initial_revenue: 27_000,
    initial_burn: 13_000,
    difficulty: "MEDIUM",
    risk_profile: "Tech hiring market slowdowns and LLM hallucination risks",
  },
  {
    name: "SupplyTrace Ledger",
    tagline: "Hardware-free container tracking and detention penalty prevention",
    sector: "Logistics",
    market: "Asia",
    business_model: "Enterprise",
    founder_strengths: ["Operations", "Sales"],
    tam: 13_000_000_000,
    initial_users: 75,
    initial_revenue: 21_000,
    initial_burn: 12_000,
    difficulty: "MEDIUM",
    risk_profile: "Resistance to digital adoption by legacy port authorities",
  },
  {
    name: "VintageSwap Vault",
    tagline: "Authenticated luxury resale community with micro-fractional shares",
    sector: "Consumer",
    market: "Global",
    business_model: "Marketplace",
    founder_strengths: ["Distribution", "Product"],
    tam: 7_800_000_000,
    initial_users: 5400,
    initial_revenue: 38_000,
    initial_burn: 23_000,
    difficulty: "HARD",
    risk_profile: "Authentication dispute liabilities and counter-party risk",
  },
  {
    name: "SolarGrid Sync",
    tagline: "Virtual power plant orchestrator for distributed residential solar",
    sector: "Climate",
    market: "Americas",
    business_model: "Infrastructure",
    founder_strengths: ["Technical", "Domain expert"],
    tam: 25_000_000_000,
    initial_users: 410,
    initial_revenue: 29_000,
    initial_burn: 16_000,
    difficulty: "HARD",
    risk_profile: "Utility grid interconnection bottlenecks and policy shifts",
  },
  {
    name: "InsureWave Cargo",
    tagline: "Parametric marine cargo insurance triggered by real-time IoT feeds",
    sector: "Fintech",
    market: "Middle East",
    business_model: "Transaction",
    founder_strengths: ["Domain expert", "Technical"],
    tam: 11_500_000_000,
    initial_users: 110,
    initial_revenue: 25_000,
    initial_burn: 14_000,
    difficulty: "MEDIUM",
    risk_profile: "Geopolitical conflict insurance exclusions and reinsurance rates",
  },
  {
    name: "DineDesk PMS",
    tagline: "All-in-one table inventory, dynamic pricing, and POS for Michelin dining",
    sector: "Food",
    market: "Europe",
    business_model: "SaaS",
    founder_strengths: ["Product", "Sales"],
    tam: 4_900_000_000,
    initial_users: 290,
    initial_revenue: 16_000,
    initial_burn: 8_500,
    difficulty: "EASY",
    risk_profile: "High restaurant turnover and razor-thin merchant operating margins",
  },
];

export const NPC_INVESTORS: NPCInvestor[] = [
  {
    id: "npc-1",
    name: "Eleanor Vance",
    firm: "Apex Horizon Ventures",
    archetype: "GENERALIST",
    avatar: "💼",
    check_size_range: [100_000, 500_000],
    preferred_sectors: ["Fintech", "SaaS", "AI", "Logistics"],
    reputation: 94,
    bio: "Multi-stage generalist backing exceptional teams tackling multi-billion dollar markets with disciplined valuations.",
    rejectionQuotes: [
      "Your market is attractive, but your current traction doesn't support the valuation ask.",
      "The TAM is large, but unit economics show negative operating leverage.",
      "Valuation expectations are ahead of the current traction profile.",
    ],
    interestQuotes: [
      "Intriguing fundamentals. We'd like to inspect your cohort retention and CAC payback.",
      "The market problem is undeniable. Send over full cap table details.",
    ],
    termSheetQuotes: [
      "We believe this company can scale. Here is our term sheet to lead your round.",
      "Clean terms, fair price. Let's build together.",
    ],
  },
  {
    id: "npc-2",
    name: "Dr. Tariq Al-Mansoor",
    firm: "DeepMoat Capital",
    archetype: "SPECIALIST",
    avatar: "🔬",
    check_size_range: [150_000, 750_000],
    preferred_sectors: ["AI", "Climate", "Healthcare", "Infrastructure"],
    reputation: 96,
    bio: "PhD technologist turned specialist investor. Prioritizes proprietary algorithms, regulatory defensibility, and organic traction.",
    rejectionQuotes: [
      "Insufficient proprietary moat. A well-funded incumbent could clone this in three quarters.",
      "Traction does not show the stickiness required for our specialized thesis.",
      "We require deeper domain defensibility before committing institutional capital.",
    ],
    interestQuotes: [
      "Your technical architecture shows promise. We want to test customer churn data.",
      "High defensibility potential. Let's see your technical milestones for next quarter.",
    ],
    termSheetQuotes: [
      "Outstanding IP and moat. We are pleased to issue this competitive term sheet.",
      "Your team has proven defensibility. We are all in.",
    ],
  },
  {
    id: "npc-3",
    name: "Marcus Thorne",
    firm: "Founders Launchpad",
    archetype: "OPERATOR",
    avatar: "⚡",
    check_size_range: [100_000, 400_000],
    preferred_sectors: ["Marketplace", "Logistics", "Consumer", "Food", "PropTech"],
    reputation: 91,
    bio: "Ex-3x unicorn founder turned venture builder. Backs relentless distribution hustlers and rapid execution cadence.",
    rejectionQuotes: [
      "Distribution velocity is sluggish. You're building features instead of acquiring customers.",
      "Founder-market execution lacks the aggressive corridor speed we look for.",
      "Burn rate is too high relative to sales velocity.",
    ],
    interestQuotes: [
      "The go-to-market engine has sparks. Show us how you scale CAC at 5x volume.",
      "Strong distribution hustle. Let's drill into your sales funnel conversion rates.",
    ],
    termSheetQuotes: [
      "You know how to sell and execute. Our operators are ready to pour fuel on your fire.",
      "Execution machine. Here is the term sheet.",
    ],
  },
];
